---
output: github_document
bibliography: doc/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# New York Airbnb Price Predictor
- authors: Ofer Mansour, Jacky Ho, Anand Vemparala 

## About

In this project, our team attempted to predict Airbnb prices in New York, using a [dataset](http://insideairbnb.com/get-the-data.html)[@GettheDa10:online] of all listings in 2019. The dataset includes 48,895  listings and includes several features, such as the price of the listing, neighbourhood, room type and number of reviews. To find the best performing prediction model, we tested several tree-based models: Random Forest, XGBoost, LightGBM and an average ensembling of the three models. 


## Report

The final report can be found here **will add link**


## Usage

To replicate this project, clone this GitHub repository, install the dependencies and run the commands below at the command line or terminal from the root directory of this project:

## Dependencies

- Python and Python Packages
  - docopt
  - requests
  - pandas
  - numpy
  - sklearn
  - lightgbm
  - xgboost
  - altair
- R
  - docopt
  - tidyverse
  - GGally
  - gridExtra
  - knitr

# References